
export const X_KEY = "251c10a4-5724-45e5-80be-f219d16a1a1d"

export const FIRST_COLOR = '#000000'
export const SECOND_COLOR = '#CC0000'
export const EXTENSO_FIRST_COLOR = 'black'
export const EXTENSO_SECOND_COLOR = 'red'
export const EXTENSO_CLEAR_COLOR = 'pink lighten-5'
export const TEXT_SYSTEM_BAR = '#FFFFFF'
export const APP_DARK = true // true a letra menu branco ou false letra menu preto


// defalut
export const SECOND_TEXT_COLOR = EXTENSO_SECOND_COLOR + '--text'
export const TOP_SYSTEM_BAR = SECOND_COLOR
export const LOADING = SECOND_COLOR
export const BREAD_CRUMB = SECOND_TEXT_COLOR
export const APP_BAR_COLOR = FIRST_COLOR
export const SOCIAL_MEDIA_COLOR = TEXT_SYSTEM_BAR
export const BOTAO_OUTLINED = TOP_SYSTEM_BAR
export const MENU_ALTERAL_FUNDO = SECOND_TEXT_COLOR + '--text text--accent-4'
export const BOTAO_PADRAO = EXTENSO_FIRST_COLOR
export const BOTAO_ATIVO = EXTENSO_SECOND_COLOR
export const UNDERLINE_WINDOW = 'text-decoration: underline; color: ' + EXTENSO_SECOND_COLOR + ';'
export const LABEL_CAROUSEL = EXTENSO_SECOND_COLOR
export const SYSTEM_BAR_COLOR = EXTENSO_SECOND_COLOR
export const CHIP_COLOR_DEFAULT = "#F5F5F5"

/*
export const FUNDO_SUB_MENU = 'red darken-2'
export const FUNDO_RODAPE = 'py-2 white--text text-center black'
export const BOTAO_OUTLINED = TOP_SYSTEM_BAR
export const TOTAL_SELECIONADO = 'red lighten-5'
export const COR_CAMPO_FORM = '#7c7c7c'
export const ITEM_SELECTBOX = 'red'
export const ICON_COLOR = 'red'
*/

/* Vertical Property Card */
export const COLOR_CODE = EXTENSO_SECOND_COLOR + '--text'
export const COLOR_ACTIONS = EXTENSO_SECOND_COLOR

export const MENU_ITEMS = [
  { id: '1', description: 'Comprar', name: 'comprar', to: '/comprar'},
  { id: '2', description: 'Alugar', name: 'alugar', to: '/alugar'},
  { id: '3', description: 'Divulgue seu Imóvel', name: 'ofertarimovel', to: '/ofertarimovel' },
  { id: '4', description: 'Fale Conosco', name: 'faleconosco', to: '/faleconosco'},
  { id: '5', description: 'Sobre Nós', name: 'sobrenos', to: '/sobrenos'}
]

export const SOCIAL_MEDIA_ITEMS = [
  { type: 'Facebook', url: 'https://www.facebook.com/', icon: 'mdi-facebook'},
  { type: 'Instagram', url: 'https://www.instagram.com/', icon: 'mdi-instagram'},
  { type: 'YouTube', url: 'https://www.youtube.com/channel/', icon: 'mdi-youtube'},
  { type: 'LinkedIn', url: 'https://www.linkedin.com/company/', icon:'mdi-linkedin'},
  { type: 'Twitter', url: 'https://twitter.com/', icon: 'mdi-twitter'},
  { type: 'TikTok', url: 'https://www.tiktok.com/@', icon: ''},
]

export const SHARE_ITEMS = [
  {id:'1', value:'facebook', img:'facebook-360.png', title:'FaceBook', share:'https://www.facebook.com/sharer/sharer.php?u='},
  {id:'2', value:'whatsapp', img:'whatsapp-360.png', title: 'WhatsApp', share:'https://api.whatsapp.com/send?text='},
  {id:'3', value:'telegram', img:'telegram-360.png', title: 'Telegram', share:'https://t.me/share/url?url='},
  {id:'4', value:'email', img:'email-360.png', title: 'E-mail', share:''},
  {id:'5', value:'copy', img:'copy-360.png', title: 'Copiar o link do site', share:''}
]

export const FALE_ITEMS = [
  {id:'1', value:'email', img:'email-360.png', title: 'E-mail', share:''},
  {id:'2', value:'whatsapp', img:'whatsapp-360.png', title: 'WhatsApp', share:'https://api.whatsapp.com/send?phone=55'},
  {id:'3', value:'phone', img:'phone-360.png', title: 'Telefone', share:''}
]

export const FINALIDADE_ITEMS = ['Comprar um imóvel', 'Alugar um imóvel','É proprietário e deseja Vender seu imóvel','É proprietário e deseja Alugar seu imóvel','É proprietário deseja Vender e Alugar seu imóvel']

export const SETOR_ITEMS = ['Venda','Locação','Venda e Locação']
export const FINALIDADES_IMOVEL = ['Residencial', 'Comercial', 'Industrial', 'Residencial / Comercial']
export const TIPO_IMOVEL_PROPERTY_ITEMS = [
    { tipo: 'Apartamento', subtipos: ['Apartamento Padrão','Cobertura','Duplex','Triplex','Kitnet','Flat','Apart hotel','Loft','Pent house','Studio','Terreo','Garden'], finalidade: ['Residencial'], extra_area: []},
    { tipo: 'Área', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial', 'Industrial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Armazem', subtipos: [], finalidade: ['Comercial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Casa', subtipos: ['Casa Padrão','Assobradada','Terrea','Sobrado'], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area:['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Chácara', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area: []},
    { tipo: 'Chalé', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area: []},
    { tipo: 'Conjunto', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area: []},
    { tipo: 'Fazenda', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area: []},
    { tipo: 'Galpāo', subtipos: [], finalidade: ['Comercial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Hotel', subtipos: [], finalidade: ['Comercial'], extra_area: []},
    { tipo: 'Loja', subtipos: [], finalidade: ['Comercial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Oportunidade Comerciais', subtipos: [], finalidade: ['Comercial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Ponto Comercial', subtipos: [], finalidade: ['Comercial'], extra_area: []},
    { tipo: 'Pousada', subtipos: [], finalidade: ['Comercial'], extra_area: []},
    { tipo: 'Predio Comercial', subtipos: [], finalidade: ['Comercial'], extra_area: []},
    { tipo: 'Sala Comercial', subtipos: [], finalidade: ['Comercial'], extra_area: []},
    { tipo: 'Salāo', subtipos: ['Salāo Padrāo','Galpāo'], finalidade: ['Comercial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
    { tipo: 'Sítio', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial'], extra_area: []},
    { tipo: 'Terreno', subtipos: [], finalidade: ['Residencial', 'Comercial','Residencial / Comercial', 'Industrial'], extra_area: ['Frente','Fundo','Lado Direito','Lado Esquerdo']},
]

export const SIM_NAO_ITEMS = ['Sim','Nāo']
export const ESTADO_IMOVEL_ITEMS = ['Pronto', 'Lançamento', 'Breve Lançamento', 'Em construção']

export const PROPERTY_ITEMS = [
  // infra
  {order:"1",description:"Água Individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Conjunto,Conjunto Comercial,Flat,Sala Comercial,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"2",description:"Andar inteiro",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Conjunto,Conjunto Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"3",description:"Aquecedor central",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Pousada"},
  {order:"4",description:"Business center",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Apartamento / Sala Comercial"},
  {order:"5",description:"Cabine primária",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Predio Comercial,Sala,Sítio"},
  {order:"6",description:"Caseiro",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"7",description:"Cerca",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"8",description:"Coffe shop",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"10",description:"Controle de acesso ao cond",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"11",description:"Curral",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Sítio,Casa"},
  {order:"12",description:"Depósito",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"13",description:"Depósito sub-solo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"14",description:"Doca",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"15",description:"Elevador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"16",description:"Elevador de carga",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"17",description:"Elevador panorâmico",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"18",description:"Elevador PNE",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"19",description:"Energia elétrica",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Sítio"},
  {order:"20",description:"Energia elétrica individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Casa,Apartamento / Sala Comercial"},
  {order:"21",description:"Energia trifásica",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Casa,Apartamento / Sala Comercial"},
  {order:"22",description:"Entrada de caminhões",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Predio Comercial,Salão,Salão Galpão"},
  {order:"23",description:"Entrada Individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"24",description:"Entrada lateral",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"25",description:"Escritório/Cowork",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Conjunto Comercial,Flat,Hotel,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"26",description:"Esgoto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Área de Incorporação,Área Industrial,Armazem,Chácara,Fazenda,Sítio"},
  {order:"27",description:"Esquina",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Loja,Oportunidade Comerciais,Ponto Comercial,Sala Comercial,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"28",description:"Estacionamento",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"29",description:"Frente mar",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Chale,Condominio Fechado,Flat,Hotel,Pousada,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"30",description:"Gás encanado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"31",description:"Gás Individualizado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"32",description:"Geminada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Sobrado,Casa / Terreno"},
  {order:"33",description:"Gerador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial"},
  {order:"34",description:"Guarita",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"35",description:"Heliponto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Apartamento / Sala Comercial"},
  {order:"36",description:"Infra internet",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"37",description:"Interfone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Flat,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"38",description:"Lago",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"39",description:"Lava rápido",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial"},
  {order:"40",description:"Lavabo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Loja,Oportunidade Comerciais,Ponto Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"41",description:"Lavanderia coletiva",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Apartamento / Sala Comercial"},
  {order:"42",description:"Lavoura",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"43",description:"Marina",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"44",description:"Mezanino",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"45",description:"Pasto",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"46",description:"Patio estacionamento",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"47",description:"Pet care",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial"},
  {order:"48",description:"Pier",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"49",description:"Piso elevado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"50",description:"Pista pouso",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Fazenda"},
  {order:"51",description:"Poço artesiano",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"52",description:"Ponte rolante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind."},
  {order:"53",description:"Portão duplo de entrada de pedestre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"54",description:"Portão duplo de entrada de veiculos",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"55",description:"Portão eletrônico",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"56",description:"Portaria Virtual",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"57",description:"Recepção",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"58",description:"Rede de telefone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"59",description:"Refeitório",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"60",description:"Reservatório de água",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Chácara,Chale,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Salão Galpão,Sítio"},
  {order:"61",description:"Restaurante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Salão Galpão"},
  {order:"62",description:"Rio",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"63",description:"Rua asfaltada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Área de Incorporação,Área Industrial,Armazem,Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"64",description:"Sacada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"65",description:"Sala de convenções",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Hotel,Oportunidade Comerciais,Predio Comercial"},
  {order:"66",description:"Segurança 24h",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"67",description:"Segurança patrimonial",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"68",description:"Sem elevador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"69",description:"Sem vaga",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"70",description:"Sistema de incêndio",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"71",description:"Sistema de segurança",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"72",description:"Solarium",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"73",description:"Telefone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"74",description:"Terraço com piscina",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"75",description:"Terraço gourmet",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"76",description:"TV a cabo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"77",description:"Vaga coberta",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"78",description:"Vaga coberta e fechada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"79",description:"Vaga demarcada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"80",description:"Vaga descoberta",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"81",description:"Vaga dupla",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"82",description:"Vaga fechada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"83",description:"Vaga livre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"84",description:"Vaga moto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"85",description:"Vaga para deficiente",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"86",description:"Vaga visitante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"87",description:"Vão livre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"88",description:"Varanda",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"89",description:"Varanda terraço",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"90",description:"Vestiário",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Hotel,Oportunidade Comerciais,Pousada,Predio Comercial,Sítio"},
  {order:"248",description:"Semi Geminada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Sobrado,Casa / Terreno"},

  {order:"91",description:"Academia",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"92",description:"Área verde",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"242",description:"Bosque",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"93",description:"Churrasqueira",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"94",description:"Forno de pizza",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"95",description:"Piscina adulto",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"96",description:"Piscina infantil",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"97",description:"Play ground",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"98",description:"Quadra poliesportiva",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"99",description:"Salão de festas",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"100",description:"Salão de jogos",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"101",description:"Sauna",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"102",description:"Brinquedoteca",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"103",description:"Cinema",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"104",description:"Bicicletario",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"105",description:"Piscina aquecida",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"106",description:"Espaço mulher",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"107",description:"Quadra tenis",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"108",description:"Skate",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"109",description:"Espaço zen",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"110",description:"Lanhouse",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"111",description:"Espaço teen",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"112",description:"SPA",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"113",description:"Pista de cooper",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"114",description:"Piscina coberta",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"115",description:"Praça",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"116",description:"Canil",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"117",description:"Campo de futebol",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"118",description:"Piscina no imóvel",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"119",description:"Quadra de squash",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"120",description:"Bar",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"121",description:"Campo de golf",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"122",description:"Espaço gourmet",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"251",description:"Clube",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"252",description:"Pista de bicicross",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},

  // private
  {order:"170",description:"Aceita PET",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"171",description:"Acessibilidade",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"172",description:"Adaptado para idoso",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"173",description:"Adega",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"174",description:"Ar condicionado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"175",description:"Área de serviço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"176",description:"Armário embutido",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"177",description:"Armário na cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"178",description:"Armário no dormitório",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"178",description:"Banheira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"179",description:"Churrasqueira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"180",description:"Claraboia",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"181",description:"Closet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"182",description:"Copa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"183",description:"Cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"184",description:"Cozinha Americana",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"185",description:"Dependência de empregado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"186",description:"Depósito",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"187",description:"Despensa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"188",description:"Dormitório reversível",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"189",description:"Edicula",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"190",description:"Elevador privativo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"191",description:"Entrada de serviço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"192",description:"Entrada lateral",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"193",description:"Envidraçada (varanda / sacada)",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"194",description:"Escritório",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"195",description:"Gesso - Sanca - Teto Rebaixado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"196",description:"Hall",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"197",description:"Hidromassagem",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"198",description:"Home Theater",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"199",description:"Jardim de Inverno",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"200",description:"Lareira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"201",description:"Lavabo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"202",description:"Lavanderia",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"203",description:"Living room",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"204",description:"Mobiliado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"205",description:"Piscina Privativa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"206",description:"Porão",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"207",description:"Quintal",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"208",description:"Rede de Segurança",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"209",description:"Sacada",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"210",description:"Sacada gourmet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"211",description:"Sacada Grill",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"212",description:"Sala de estar",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"213",description:"Sala de estudo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"214",description:"Sala de jantar",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"215",description:"Sala de TV",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"216",description:"Sala Intima",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"217",description:"Semi mobiliado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"218",description:"Solarium",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"219",description:"Soton",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"220",description:"Terraço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"221",description:"Terraço gourmet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"222",description:"Terraço Grill",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"223",description:"Varanda",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"224",description:"Ventilador de teto",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"225",description:"WC empregado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"243",description:"Fogão",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"244",description:"Freezer",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"245",description:"Geladeira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"246",description:"Lavadora de Roupas",model:"private_areas",regioes:null,default:"0",tipos:null,created_at:null,updated_at:null},
  {order:"247",description:"Micro ondas",model:"private_areas",regioes:null,default:"0",tipos:null,created_at:null,updated_at:null},
  {order:"249",description:"TV",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"250",description:"Utensilho Cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
]


export const INFRA_ITEMS = [
  // infra
  {order:"1",description:"Água Individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Conjunto,Conjunto Comercial,Flat,Sala Comercial,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"2",description:"Andar inteiro",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Conjunto,Conjunto Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"3",description:"Aquecedor central",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Pousada"},
  {order:"4",description:"Business center",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Apartamento / Sala Comercial"},
  {order:"5",description:"Cabine primária",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Predio Comercial,Sala,Sítio"},
  {order:"6",description:"Caseiro",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"7",description:"Cerca",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"8",description:"Coffe shop",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"10",description:"Controle de acesso ao cond",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"11",description:"Curral",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Sítio,Casa"},
  {order:"12",description:"Depósito",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"13",description:"Depósito sub-solo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"14",description:"Doca",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"15",description:"Elevador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"16",description:"Elevador de carga",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"17",description:"Elevador panorâmico",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"18",description:"Elevador PNE",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"19",description:"Energia elétrica",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Chácara,Sítio"},
  {order:"20",description:"Energia elétrica individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Casa,Apartamento / Sala Comercial"},
  {order:"21",description:"Energia trifásica",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Casa,Apartamento / Sala Comercial"},
  {order:"22",description:"Entrada de caminhões",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Predio Comercial,Salão,Salão Galpão"},
  {order:"23",description:"Entrada Individualizada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"24",description:"Entrada lateral",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"25",description:"Escritório/Cowork",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Conjunto Comercial,Flat,Hotel,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"26",description:"Esgoto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Área de Incorporação,Área Industrial,Armazem,Chácara,Fazenda,Sítio"},
  {order:"27",description:"Esquina",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Loja,Oportunidade Comerciais,Ponto Comercial,Sala Comercial,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"28",description:"Estacionamento",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"29",description:"Frente mar",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Chale,Condominio Fechado,Flat,Hotel,Pousada,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"30",description:"Gás encanado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"31",description:"Gás Individualizado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"32",description:"Geminada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Sobrado,Casa / Terreno"},
  {order:"33",description:"Gerador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto Comercial,Loja,Ponto Comercial,Predio Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial"},
  {order:"34",description:"Guarita",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"35",description:"Heliponto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Apartamento / Sala Comercial"},
  {order:"36",description:"Infra internet",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"37",description:"Interfone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Flat,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"38",description:"Lago",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"39",description:"Lava rápido",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial"},
  {order:"40",description:"Lavabo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Loja,Oportunidade Comerciais,Ponto Comercial,Sala Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"41",description:"Lavanderia coletiva",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Hotel,Apartamento / Sala Comercial"},
  {order:"42",description:"Lavoura",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"43",description:"Marina",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"44",description:"Mezanino",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"45",description:"Pasto",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"46",description:"Patio estacionamento",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"47",description:"Pet care",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial"},
  {order:"48",description:"Pier",model:"infrastructures",regioes:"Litoral",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Pousada,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"49",description:"Piso elevado",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto Comercial,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"50",description:"Pista pouso",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Fazenda"},
  {order:"51",description:"Poço artesiano",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"52",description:"Ponte rolante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind."},
  {order:"53",description:"Portão duplo de entrada de pedestre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"54",description:"Portão duplo de entrada de veiculos",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"55",description:"Portão eletrônico",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Condominio Fechado,Conjunto,Conjunto Comercial,Loja,Oportunidade Comerciais,Ponto Comercial,Sobrado,Casa / Terreno"},
  {order:"56",description:"Portaria Virtual",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"57",description:"Recepção",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Condominio Fechado,Conjunto,Conjunto Comercial,Flat,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Apartamento / Sala Comercial"},
  {order:"58",description:"Rede de telefone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"59",description:"Refeitório",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"60",description:"Reservatório de água",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Chácara,Chale,Fazenda,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Salão Galpão,Sítio"},
  {order:"61",description:"Restaurante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Salão Galpão"},
  {order:"62",description:"Rio",model:"infrastructures",regioes:"Campo",default:"0",tipos:"Chácara,Condominio Fechado,Pousada,Fazenda,Sítio,Sobrado"},
  {order:"63",description:"Rua asfaltada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Área de Incorporação,Área Industrial,Armazem,Chácara,Chale,Fazenda,Pousada,Sítio"},
  {order:"64",description:"Sacada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Área de Incorporação,Área Industrial,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"65",description:"Sala de convenções",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Conjunto,Conjunto Comercial,Hotel,Oportunidade Comerciais,Predio Comercial"},
  {order:"66",description:"Segurança 24h",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Pousada,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Sítio,Sobrado,Terreno,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"67",description:"Segurança patrimonial",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"68",description:"Sem elevador",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"69",description:"Sem vaga",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"70",description:"Sistema de incêndio",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"71",description:"Sistema de segurança",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"72",description:"Solarium",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"73",description:"Telefone",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"74",description:"Terraço com piscina",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"75",description:"Terraço gourmet",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"76",description:"TV a cabo",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"77",description:"Vaga coberta",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"78",description:"Vaga coberta e fechada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"79",description:"Vaga demarcada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"80",description:"Vaga descoberta",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"81",description:"Vaga dupla",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"82",description:"Vaga fechada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"83",description:"Vaga livre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"84",description:"Vaga moto",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"85",description:"Vaga para deficiente",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"86",description:"Vaga visitante",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Condominio Fechado,Flat,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"87",description:"Vão livre",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Conjunto,Conjunto Comercial,Galpão,Galpão c/ Mor.,Galpão Com.,Galpão Ind.,Hotel,Loja,Oportunidade Comerciais,Ponto Comercial,Predio Comercial,Sala Comercial,Salão,Salão Galpão,Apartamento / Sala Comercial"},
  {order:"88",description:"Varanda",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"89",description:"Varanda terraço",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"90",description:"Vestiário",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Armazem,Condominio Fechado,Conjunto,Conjunto Comercial,Fazenda,Flat,Hotel,Oportunidade Comerciais,Pousada,Predio Comercial,Sítio"},
  {order:"248",description:"Semi Geminada",model:"infrastructures",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Assobradada,Casa,Sobrado,Casa / Terreno"},
]

export const RECREATION_ITEMS = [
  {order:"91",description:"Academia",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"92",description:"Área verde",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"242",description:"Bosque",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"93",description:"Churrasqueira",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"94",description:"Forno de pizza",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"95",description:"Piscina adulto",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"96",description:"Piscina infantil",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"97",description:"Play ground",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"98",description:"Quadra poliesportiva",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"99",description:"Salão de festas",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"100",description:"Salão de jogos",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"101",description:"Sauna",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"102",description:"Brinquedoteca",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"103",description:"Cinema",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"104",description:"Bicicletario",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"105",description:"Piscina aquecida",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"106",description:"Espaço mulher",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"107",description:"Quadra tenis",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"108",description:"Skate",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"109",description:"Espaço zen",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"110",description:"Lanhouse",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:""},
  {order:"111",description:"Espaço teen",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"112",description:"SPA",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"113",description:"Pista de cooper",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"114",description:"Piscina coberta",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"115",description:"Praça",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"116",description:"Canil",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"117",description:"Campo de futebol",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"118",description:"Piscina no imóvel",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"119",description:"Quadra de squash",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"120",description:"Bar",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"121",description:"Campo de golf",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"122",description:"Espaço gourmet",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"251",description:"Clube",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
  {order:"252",description:"Pista de bicicross",model:"recreations",regioes:"Urbana, Litoral, Campo",default:"0",tipos:"Apartamento,Assobradada,Casa,Chácara,Chale,Condominio Fechado,Fazenda,Flat,Hotel,Pousada,Sítio,Sobrado,Apartamento / Sala Comercial,Casa / Terreno"},
]

export const PRIVATE_ITEMS = [
  // private
  {order:"170",description:"Aceita PET",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"171",description:"Acessibilidade",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"172",description:"Adaptado para idoso",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"173",description:"Adega",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"174",description:"Ar condicionado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"175",description:"Área de serviço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"176",description:"Armário embutido",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"177",description:"Armário na cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"178",description:"Armário no dormitório",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"178",description:"Banheira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"179",description:"Churrasqueira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"180",description:"Claraboia",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"181",description:"Closet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"182",description:"Copa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"183",description:"Cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"184",description:"Cozinha Americana",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"185",description:"Dependência de empregado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"186",description:"Depósito",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"187",description:"Despensa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"188",description:"Dormitório reversível",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"189",description:"Edicula",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"190",description:"Elevador privativo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"191",description:"Entrada de serviço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"192",description:"Entrada lateral",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"193",description:"Envidraçada (varanda / sacada)",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"194",description:"Escritório",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"195",description:"Gesso - Sanca - Teto Rebaixado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"196",description:"Hall",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"197",description:"Hidromassagem",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"198",description:"Home Theater",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"199",description:"Jardim de Inverno",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"200",description:"Lareira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"201",description:"Lavabo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"202",description:"Lavanderia",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"203",description:"Living room",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"204",description:"Mobiliado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"205",description:"Piscina Privativa",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"206",description:"Porão",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"207",description:"Quintal",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"208",description:"Rede de Segurança",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"209",description:"Sacada",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"210",description:"Sacada gourmet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"211",description:"Sacada Grill",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"212",description:"Sala de estar",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"213",description:"Sala de estudo",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"214",description:"Sala de jantar",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"215",description:"Sala de TV",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"216",description:"Sala Intima",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"217",description:"Semi mobiliado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"218",description:"Solarium",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"219",description:"Soton",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"220",description:"Terraço",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"221",description:"Terraço gourmet",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"222",description:"Terraço Grill",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"223",description:"Varanda",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"224",description:"Ventilador de teto",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"225",description:"WC empregado",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"243",description:"Fogão",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"244",description:"Freezer",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"245",description:"Geladeira",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"246",description:"Lavadora de Roupas",model:"private_areas",regioes:null,default:"0",tipos:null,created_at:null,updated_at:null},
  {order:"247",description:"Micro ondas",model:"private_areas",regioes:null,default:"0",tipos:null,created_at:null,updated_at:null},
  {order:"249",description:"TV",model:"private_areas",regioes:null,default:"0",tipos:null},
  {order:"250",description:"Utensilho Cozinha",model:"private_areas",regioes:null,default:"0",tipos:null},
]

export const MONEY =  {
  decimal: ',',
  thousands: '.',
  prefix: 'R$ ',
  suffix: '',
  precision: 2,
  masked: false,
  min: Number.MIN_SAFE_INTEGER,
  max: Number.MAX_SAFE_INTEGER
}
